services:
  anadoli-next:
    container_name: anadoli-next
    restart: always
    image: node:20.10.0
    ports:
      - '4000:3000'
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/anadoli-next
    working_dir: /usr/src/anadoli-next

    networks:
      - client-network

    # FRO PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
